//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public int StudentUserID { get; set; }
        public int InstructorUserID { get; set; }
        public System.DateTime Time { get; set; }
        public bool IsConfirmed { get; set; }
        public System.Guid confirmCode { get; set; }
        public int OriginalAvailID { get; set; }
    }
}
