//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        public int FileID { get; set; }
        public int UserID { get; set; }
        public byte[] FileContent { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int FileSize { get; set; }
    }
}
